package arduboy

import (
	"html/template"
	"io"
	"time"
)

const FlashcartMetaTemplate = `
<!DOCTYPE html>
<html>
<head>
  <title>{{.Device}} Flashcart</title>
  <meta charset="UTF-8">
  <meta name="description" content="Generated by ardugotools">
  <style>
    body {
      max-width: 800px;
    }
    img {
      float: right;
      margin-left: 1em;
    }
    hr {
      clear: both;
    }
    .categoryinfo {
      background-color: yellow;
    }
  </style>
</head>
<body>
  <h1>{{.Device}} Flashcart {{.Date}}</h1>
  {{range .Categories}}
  <div class="category">
    <div class="categoryinfo">
      {{if .Image}}
        <img src="{{decodeDataUrl .Image}}">
      {{end}}
      <h2>{{.Title}}</h2>
      <p class="description">{{.Info}}</p>
      <hr>
    </div>
    <div class="programlist">
      {{range .Slots}}
      <div class="program">
        {{if .Image}}
          <img src="{{decodeDataUrl .Image}}">
        {{end}}
        <h3>{{.Title}}</h3>
        <p class="meta">Version {{.Version}} - {{.Developer}}</p>
        <p class="description">{{.Info}}</p>
      </div>
      {{end}}
    </div>
  </div>
  {{end}}
</body>
</html>
`

func RenderFlashcartMeta(categories []HeaderCategory, device *ExtendedDeviceInfo, destination io.Writer) error {
	funcMap := template.FuncMap{
		"decodeDataUrl": func(data string) template.URL {
			return template.URL(data)
		},
	}
	t, err := template.New("index").Funcs(funcMap).Parse(FlashcartMetaTemplate)
	if err != nil {
		return err
	}
	data := make(map[string]interface{})
	data["Categories"] = categories
	data["Device"] = device.Bootloader.Device
	data["Date"] = time.Now().Format(time.RFC1123)
	t.Execute(destination, data)
	return nil
}
